// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxpp_qObeJ19bOhBH5vOizTfmCP3Y5NJw',
    appId: '1:823247218060:web:6e5893725ece3fe79c22a9',
    messagingSenderId: '823247218060',
    projectId: 'thanos3dtask',
    authDomain: 'thanos3dtask.firebaseapp.com',
    storageBucket: 'thanos3dtask.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD-jOWHhPbyF76v9kr1aYyjfELGlSs9M8',
    appId: '1:216449937960:android:022a7bcbda4f67ca5dfb1d',
    messagingSenderId: '216449937960',
    projectId: 'test-react-794a6',
    storageBucket: 'test-react-794a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVkiv7xgddC6DeZIv_mNq7ZCtI5m5eMk4',
    appId: '1:823247218060:ios:9743bbdef68f763a9c22a9',
    messagingSenderId: '823247218060',
    projectId: 'thanos3dtask',
    storageBucket: 'thanos3dtask.appspot.com',
    iosBundleId: 'com.example.thanos3dtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVkiv7xgddC6DeZIv_mNq7ZCtI5m5eMk4',
    appId: '1:823247218060:ios:9743bbdef68f763a9c22a9',
    messagingSenderId: '823247218060',
    projectId: 'thanos3dtask',
    storageBucket: 'thanos3dtask.appspot.com',
    iosBundleId: 'com.example.thanos3dtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxpp_qObeJ19bOhBH5vOizTfmCP3Y5NJw',
    appId: '1:823247218060:web:3fdd5998b50d6d739c22a9',
    messagingSenderId: '823247218060',
    projectId: 'thanos3dtask',
    authDomain: 'thanos3dtask.firebaseapp.com',
    storageBucket: 'thanos3dtask.appspot.com',
  );

}